name: kartograph
description: Flutter map prohect that is needed to fill
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  elementary: ^1.3.1
  firebase_crashlytics: ^2.7.2
  flutter_localizations:
    sdk: flutter
  logger: ^1.1.0
  provider: ^6.0.2
  surf_logger: ^1.1.0
  adaptive_navigation: ^0.0.7
#  библиотеки для сервиса
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
#  навигация
  routemaster: ^1.0.0
#  иконки
  flutter_svg: ^1.1.0
#  библиотеки для работы с сервером
#  flutter pub run build_runner build
  json_annotation: ^4.5.0
  json_serializable: ^6.2.0
  dio: ^4.0.6
  retrofit: ^3.0.1+1
#  библиотеки отвечающие за работу с картами
  map: ^1.0.1
  latlng: ^0.1.0
  cached_network_image: ^3.2.1
# геолокация
  geolocator: ^8.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.10
  dart_code_metrics: ^4.15.1
  elementary_test: ^1.1.1
  json_serializable: ^6.2.0
  retrofit_generator: ^4.0.1
  surf_lint_rules: ^1.5.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
